Chore: Fix/remove tools (fixes #471)
eslint/espree pull request #476
Opened 2021-04-16 17:54 UTC by nzakas

1. I removed a bunch of scripts in the `tools/` directory that were left over from the initial Esprima migration and were no longer used.
2. For tools that were heavily reliant on `require()`, I opted to just rename the file to `.cjs`.

2021-04-19 03:42 UTC, btmills approved these changes

2021-04-19 14:03 UTC, mdjermanovic requested changes
We should also update both `create-test.js` and `update-tests.js` to produce ESM content in `*.result.js` files, because the tests will import those files and all `*.js` files are now ESM. In particular, we should replace `module.exports =` with `export default` [here](https://github.com/eslint/espree/blob/5dd3dee83616838451adad7183dd3dd8499a7335/tools/create-test.js#L97) and [here](https://github.com/eslint/espree/blob/5dd3dee83616838451adad7183dd3dd8499a7335/tools/update-tests.js#L54).

2021-04-19 17:12 UTC, nzakas commented on tools/update-tests.cjs
>      tester = require("../tests/lib/tester"),
Doh! Unsure how I missed this. Thanks.

2021-04-19 17:25 UTC, nzakas commented
Should be set now. Also found that the scripts didn't work with the bigint tests, so fixed that too.

2021-04-20 01:02 UTC, mdjermanovic approved these changes
LGTM!

2021-04-20 01:03 UTC, mdjermanovic commented
There's a merge conflict in `package.json`.

2021-04-21 00:41 UTC, nzakas commented
Conflict fixed.

2021-04-21 00:41 UTC, merged